apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agents
resources:
  - namespace.yaml
  - agent.yaml
  - relay.yaml
  - network-policies.yaml
configMapGenerator:
  - name: agent-vault-relay-config
    files:
      - relay.toml
