apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - reconciler.yaml
configMapGenerator:
  - name: agent-vault-config
    files:
      - server.toml
  - name: agent-vault-fleet-desired
    files:
      - base.toml=desired-state/base.toml
      - environment.toml=desired-state/production.toml
