apiVersion: v1
kind: Service
metadata:
  name: agent-vault
  labels:
    app.kubernetes.io/name: agent-vault
    app.kubernetes.io/component: broker
spec:
  selector:
    app.kubernetes.io/name: agent-vault
    app.kubernetes.io/component: broker
  ports:
    - name: api
      port: 443
      targetPort: api
    - name: proxy
      port: 14322
      targetPort: proxy
